language: node_js

node_js: stable

install:
  - npm install -g hexo-cli
  - npm install

before_script:
  - mkdir pages
  - cd pages
  - hexo version
  - hexo init 

script:
  - git init
  - git submodule add https://github.com/theme-next/hexo-theme-next.git themes/next
  - git submodule update --recursive --init

after_script:
  - git config --list
  - git config user.name "zhangyubo"
  - git config user.email "cscrypto@163.com"
  - git add .
  - git commit -m "Deploy blog pages"
  - echo $PAGES_SRC_TOKEN
  - git push --force "https://${PAGES_SRC_TOKEN}@github.com/YuboZhang/YuboZhang.github.io" master:gh-pages

branches:
  only:
    - master

token: $PAGES_SRC_TOKEN