os: linux

language: node_js

node_js: stable

branches:
   only:
     - master 

cache:
   directories:
     - node_modules

before_script:
   - npm install -g hexo-cli
   - npm install hexo-symbols-count-time --save
   - npm install

script:
   - hexo clean
   - hexo generate

# after_script:
  # - cd ./public
  # - git init
  # - git config --list
  # - git config user.name "zhangyubo"
  # - git config user.email "cscrypto@163.com"
  # - git add .
  # - git commit -m "Deploy blog pages"
  # - git push --quiet "https://${PAGES_SRC_TOKEN}@github.com/YuboZhang/YuboZhang.github.io" origin gh-pages

deploy:
   provider: pages
   skip_cleanup: true
   strategy: git
   token: $PAGES_SRC_TOKEN  #master
   keep_history: true
   on:
      branch: master
   local_dir: public
   target_branch: gh-pages
   email: cscrypto@163.com
   name: zhangyubo

