language: node_js

node_js: stable

install:
  - npm install

before_script:
  - mkdir pages
  - cd pages
  - git clone https://github.com/theme-next/hexo-theme-next.git themes/next

script:
  - hexo init 

after_script:
  - git init
  - git config user.name "zhangyubo"
  - git config user.email "cscrypto@163.com"
  - git add .
  - git commit -m "Deploy blog pages"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/YuboZhang/YuboZhang.github.io" origin gh-pages

branches:
  only:
    - master
