os: linux

language: node_js

node_js: stable

branches:
   only:
     - master 

cache:
   directories:
     - node_modules

before_script:
   - npm install -g hexo-cli
   - git clone git@github.com:theme-next/hexo-theme-next.git theme/next
   - npm install

script:
   - hexo generate

deploy:
   provider: pages
   skip_cleanup: true
   token: $GITHUB_TOKEN
   keep_history: true
   on:
      branch: master
   local_dir: public
   target_branch: gh-pages

