name: 'github pages'

on:
  push:
    branches:
      - master

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
          #cache: npm
      - name: install hexo
        run: |
             npm install -g hexo-cli
             npm install hexo-symbols-count-time --save
             npm install hexo-math --save
             npm uninstall hexo-renderer-marked --save
             wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
             sudo dpkg -i pandoc-2.10.1-1-amd64.deb  # install pandoc before hexo-renderer-pandoc
             npm install hexo-renderer-pandoc --save # for mathjax
             npm install
             npm update
      - name: pull git repository
        run:  gh repo clone YuboZhang/YuboZhang.github.io
      - name: run hexo
        run: |
             hexo version
             hexo clean
             hexo generate
      - name: push to repository
        run: |
             ls -l ${{ github.workspace }}
             git config --global user.name "zhangyubo"
             git config --global user.email "cscrypto@163.com"
             git add .
             git commit -m "Deploy blog pages"
             git push origin gh-pages
