name: 'github pages'

on:
  push:
    branches:
      - master

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 17.9.0
          #cache: npm
      - run: npm install -g hexo-cli
      - run: npm install hexo-symbols-count-time --save
      - run: npm install hexo-math --save
      - run: npm uninstall hexo-renderer-marked --save
      - run: wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
      - run: sudo dpkg -i pandoc-2.10.1-1-amd64.deb  # install pandoc before hexo-renderer-pandoc
      - run: npm install hexo-renderer-pandoc --save # for mathjax
      - run: npm install
      - run: npm update
      - run: hexo version
      - run: hexo clean
      - run: hexo generate
      - name: Check out repository code
        uses: actions/checkout@v3